name: Copilot Seat Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  analyze-seats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Copilot seat analysis
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        run: python copilot-seat-analysis.py

      - name: Upload seat analysis as artifact
        uses: actions/upload-artifact@v4
        with:
          name: copilot-seat-analysis
          path: copilot-seat-analysis.csv
